### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by jujuWork** [jujuWork/BOOKSHELF#1]

**Comment by aniruddha76** [comment]
is there any issue? it only says icon

**Comment by jujuWork** [comment]
![logo](https://github.com/jujuWork/BOOKSHELF/assets/151762647/fe232d99-6283-42f4-937b-60e4beec66ec)

**Comment by aniruddha76** [comment]
could you elaborate this issue?

**Comment by jujuWork** [comment]
sorry this is only a test to upload this icon into my website…
